/**
 * Terms & Conditions content — single source of truth rendered by
 * `TermsSheet` (onboarding + Settings) and referenced when recording
 * acceptance on the athlete profile (`termsAcceptedAt`/`termsVersion`).
 *
 * This is a plain-language liability/assumption-of-risk disclaimer, not a
 * substitute for review by a lawyer before any public release — see CLAUDE.md
 * §1 (audience is currently the author + a few friends).
 */

/** Bump whenever the substance of the terms changes, so a future re-prompt
 * ("terms updated, please re-accept") can compare against `termsVersion`. */
export const TERMS_VERSION = '2026-08-07';

export interface TermsSection {
  title: string;
  body: string;
}

export const TERMS_SECTIONS: TermsSection[] = [
  {
    title: 'Who we are',
    body:
      'CoachFit is developed and maintained by Bright Angle, LLC, a Maryland limited ' +
      'liability company ("we," "us," "Bright Angle"). By using CoachFit you agree to ' +
      'these terms.',
  },
  {
    title: 'Not medical advice',
    body:
      'CoachFit is a self-directed training tool, not a medical device, physician, or ' +
      'licensed personal trainer. Nothing in the app is medical advice or a substitute ' +
      'for it. Talk to a doctor before starting this or any exercise program, especially ' +
      'if you are pregnant, have a heart condition, joint or muscle injury, or any ' +
      'condition that exercise could make worse.',
  },
  {
    title: 'Assumption of risk',
    body:
      'Exercise carries inherent risk of injury, including sprains, strains, fractures, ' +
      'cardiovascular events, and in rare cases death, even when a program is followed ' +
      'exactly as written. By using CoachFit you voluntarily accept these risks for ' +
      'yourself.',
  },
  {
    title: 'Your responsibility',
    body:
      'You are responsible for using safe form, using equipment that is in good repair, ' +
      'training in a safe environment, and stopping immediately if something hurts or ' +
      'feels wrong. The "anything bothering you today?" prompt and target/avoid areas ' +
      'help the app steer around known issues, but they only work if you keep them ' +
      'up to date — the app has no way to know what it hasn\'t been told.',
  },
  {
    title: 'No guarantee of results',
    body:
      'Workouts are generated by a deterministic rules engine from the goals, equipment, ' +
      'readiness, and history you provide. It adapts as a trainer would, but it cannot ' +
      'see or examine you, and it cannot guarantee any particular outcome, pace of ' +
      'progress, or that a given session is appropriate for your individual health ' +
      'status.',
  },
  {
    title: 'Estimated metrics, not clinical measurements',
    body:
      'Calorie burn, strength, and endurance figures are estimates derived from ' +
      'self-reported data and published formulas (MET values, Epley 1RM estimation, ' +
      'session-RPE). They are for motivation and trend-tracking, not clinical or medical ' +
      'measurement.',
  },
  {
    title: 'Exercise demo media',
    body:
      'Illustrations, stills, and any linked video clips shown for an exercise are ' +
      'included for demonstration only, with sourcing/attribution shown in-app where ' +
      'applicable. They do not replace being shown proper form by a qualified ' +
      'professional in person.',
  },
  {
    title: 'Ownership',
    body:
      'CoachFit — including its software, rules engine, exercise library, illustrations, ' +
      'and associated trademarks — is owned by Bright Angle, LLC and protected by ' +
      'copyright and other intellectual property laws. Your license to use the app (below) ' +
      'doesn\'t transfer ownership of any of it to you.',
  },
  {
    title: 'License to use the app',
    body:
      'You get a personal, non-exclusive, non-transferable, revocable license to use ' +
      'CoachFit on devices you own or control, for your own personal, non-commercial use, ' +
      'subject to these terms and Apple\'s standard End User License Agreement.',
  },
  {
    title: 'Purchase',
    body:
      'CoachFit is available for a single, one-time purchase ($3.99 USD, or the equivalent ' +
      'shown in the App Store for your region) processed entirely through Apple. There are ' +
      'no subscriptions, no recurring charges, and no in-app purchases. Refunds are handled ' +
      'by Apple under its standard App Store refund policy — we don\'t process payments or ' +
      'refunds directly.',
  },
  {
    title: 'Acceptable use',
    body:
      'You agree not to reverse-engineer, decompile, or extract the app\'s source code ' +
      'except where the law allows it; remove or alter proprietary notices; scrape or copy ' +
      'the exercise library for use outside the app; or otherwise use the app unlawfully or ' +
      'in a way that interferes with its operation or security.',
  },
  {
    title: 'Third-party content and services',
    body:
      'Future versions of CoachFit may show exercise demonstration media sourced from ' +
      'third parties, credited to their original creator in-app. We don\'t control ' +
      'third-party content, platforms, or services, and aren\'t responsible for their ' +
      'availability or accuracy. Where CoachFit integrates with a platform like Apple ' +
      'Health, that integration is also governed by that platform\'s own terms.',
  },
  {
    title: 'Limitation of liability',
    body:
      'To the fullest extent permitted by law, Bright Angle, LLC is not liable for any ' +
      'injury, loss, or damage arising from your use of CoachFit, except where caused by ' +
      'gross negligence or willful misconduct. You use the app, and act on what it tells ' +
      'you, at your own risk.',
  },
  {
    title: 'Eligibility',
    body:
      'CoachFit is intended for adults (18+). If you are under 18, only use it with the ' +
      'involvement and consent of a parent or guardian.',
  },
  {
    title: 'Privacy',
    body:
      'How CoachFit handles your data is covered in a separate Privacy Policy — see ' +
      '"Privacy Policy" in Settings, or the acceptance step alongside these terms. In ' +
      'short: everything stays on your device unless you choose to write a workout to ' +
      'Apple Health.',
  },
  {
    title: 'Governing law and disputes',
    body:
      'These terms are governed by the laws of the State of Maryland, without regard to ' +
      'conflict-of-law principles. If you have a concern, please reach out first — most ' +
      'issues can be resolved directly, faster than through a formal proceeding.',
  },
  {
    title: 'Changes to these terms',
    body:
      'These terms may be updated as the app evolves. Continuing to use CoachFit after ' +
      'an update means you accept the revised terms.',
  },
];
